import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "@/hooks/auth";
import { getServerSession } from "next-auth";
import { authOptions } from "@/utils";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Tgcc upsit mini",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const SessionProvider =  await getServerSession(authOptions)
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <Provider session={SessionProvider}>

        {children}
        </Provider>
      </body>
    </html>
  );
}
